Repository X-lab2017/OSSDevGov2021, pull requests merged in 2021-04, with the labels that each got.

#14 [Docs] delete DS_Store file
  .DS_Store
  software_engineering_at_google/.DS_Store
Labels: area/document, pull/approved

#19 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: pull/approved

#25 [Refactor] Update role accounts
  .github/hypertrons.json
Labels: kind/enhancement
